services:
  mssql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: cinema_mssql
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourPassword123!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql_data:/var/opt/mssql

  nats:
    image: "nats:latest"
    container_name: cinema_nats
    ports:
      - "4222:4222"
      - "8222:8222"

volumes:
  mssql_data:
